import 'bulma/css/bulma.min.css';
import Head from 'next/head';
import Search from '../components/Search';
import MyProvider from '../context/myProvider';

export default function Home() {
  return (
    <MyProvider>
      <Head>
        <title>NetMovies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
    </MyProvider>
  );
}
