import Head from 'next/head';
import MyProvider from '../context/myProvider';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <MyProvider>
      <Head>
        <title>NetMovies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Iniciando projeto</h1>
    </MyProvider>
  );
}
